# Generated by Django 5.1.3 on 2024-11-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creator',
        ),
    ]
